const WALLETS_SET_STATE: 'WALLETS_SET_STATE' = 'WALLETS_SET_STATE';

const WALLETS_METAMASK_CONNECT: 'WALLETS_METAMASK_CONNECT' = 'WALLETS_METAMASK_CONNECT';

const WALLETS_WHITELIST: 'WALLETS_WHITELIST' = 'WALLETS_WHITELIST';
const WALLETS_CHECK_IS_WHITELISTED: 'WALLETS_CHECK_IS_WHITELISTED' = 'WALLETS_CHECK_IS_WHITELISTED';

const WALLETS_SIGN_BUY: 'WALLETS_SIGN_BUY' = 'WALLETS_SIGN_BUY';

const WALLETS_DISCONNECT: 'WALLETS_DISCONNECT' = 'WALLETS_DISCONNECT';

export default {
  WALLETS_SET_STATE,

  WALLETS_METAMASK_CONNECT,

  WALLETS_WHITELIST,
  WALLETS_CHECK_IS_WHITELISTED,

  WALLETS_SIGN_BUY,

  WALLETS_DISCONNECT,
};
