const WEB3_CONNECT:'WEB3_CONNECT' = 'WEB3_CONNECT';
const WEB3_CONNECT_SUCCESS:'WEB3_CONNECT_SUCCESS' = 'WEB3_CONNECT_SUCCESS';
const WEB3_CONNECT_ERROR:'WEB3_CONNECT_ERROR' = 'WEB3_CONNECT_ERROR';
const WEB3_CONNECT_RESET:'WEB3_CONNECT_RESET' = 'WEB3_CONNECT_RESET';

export default {
  WEB3_CONNECT,
  WEB3_CONNECT_SUCCESS,
  WEB3_CONNECT_ERROR,
  WEB3_CONNECT_RESET,
};
